services:
  db:
    image: postgres:15-alpine
    container_name: social_media_db
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_media_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/social_media
      RABBIT_HOST: queue
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data/thumbs:/app/data/thumbs
    working_dir: /app/backend
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn rest_api:app --host 0.0.0.0 --port 8000 --reload

  queue:
    image: rabbitmq:3-management
    container_name: social_media_queue
    ports:
      - "5672:5672"   
      - "15672:15672" 

  resize_worker:
    build:
      context: .
      dockerfile: backend/resize_service/Dockerfile
    container_name: social_media_resize_worker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/social_media
      RABBIT_HOST: queue
      RESIZE_QUEUE: resize
      THUMB_DIR: /data/thumbs
      THUMB_PUBLIC_PREFIX: /thumbs
      THUMB_SIZE: 256
    volumes:
      - ./data/thumbs:/data/thumbs
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_started

  ml_service:
    build:
      context: .
      dockerfile: backend/ml_service/Dockerfile
    container_name: social_media_ml_service
    environment:
      RABBIT_HOST: queue
      ML_QUEUE: sentiment
    depends_on:
      queue:
        condition: service_started


volumes:
  postgres_data:

  